### ISSUE TITLE
Node arguments?

### ISSUE THREAD

**Issue by alewcock** [sysgears/spinjs#21]
Is it possible to specify command line arguments to be passed to node?

I am trying to use Visual Studio Code to debug, and it requires the --inspect flag to be passed to node on startup.

Thanks!

**Comment by vlasenko** [comment]
@alewcock At the moment no. But Pull Request would be welcome. I believe we can detect node version and pass `--inspect` or `--debug` in development mode to backend process:
https://github.com/sysgears/spinjs/blob/9c7a6c3eddf4eda64450c5eb8ae9a6cf3f4b8751/src/executor.ts#L51

**Comment by alewcock** [comment]
Thank you!
