### ISSUE TITLE
__dirname return '/'

### ISSUE THREAD

**Issue by lyudad** [sysgears/spinjs#22]
> "options": {
>         "backendBuildDir": "backend/dist",
>         "frontendBuildDir": "frontend/dist",
>         "dllBuildDir": ".build/dll",
>         "overridesConfig": "tools/webpackAppConfig.js",
>         "stack": [
>             "apollo",
>             "ts",
>             "react",
>             "webpack",
>             "css"
>         ],
>         "webpackDevPort": 3009,
>         "apiPort": 8080,
>         "defines": {
>             "__GRAPHQL_URL__": "path"
>         },
>         "ssr": false,
>         "useDefaultPostCss": true,
>         "webpackDll": true,
>         "reactHotLoader": false,
>         "persistGraphQL": false,
>         "frontendRefreshOnBackendChange": true,
>         "apolloLogging": true
>     }

OUTPUT does not have __dirname: true

> spin watch "-v"

> spin debug webDll =  { name: 'webDll',
>   devtool: '#cheap-module-source-map',
>   module:
>    { rules:
>       [ { test: /\.tsx?$/,
>           use:
>            [ { loader: 'loaderPath',
>                options: { configFileName: 'configPath' } } ] },
>         { test: /\.html$/,
>           loader: 'loaderPath } ] },
>   resolve:
>    { modules:
>       [ 'node_modulesPath',
>         'node_modules' ],
>      extensions:
>       [ '.web.tsx',
>         '.web.ts',
>         '.web.jsx',
>         '.web.js',
>         '.tsx',
>         '.ts',
>         '.jsx',
>         '.js' ] },
>   watchOptions: { ignored: /build/ },
>   bail: false,
>   plugins:
>    [ DefinePlugin {
>        definitions: { __DEV__: true, 'process.env.NODE_ENV': '"development"' } },
>      DllPlugin {
>        options: { name: 'vendor_web', path: '.build/dll/vendor_web_dll.json' } },
>      CheckerPlugin {} ],
>   node: { fs: 'empty', net: 'empty', tls: 'empty' },
>   entry:
>    { vendor:
>       [ 'ajv',
>         'apollo-client',
>         'apollo-link',
>         'apollo-logger',
>         'browser-bunyan',
>         'redux-injectable-reducer',
>         'redux-injectable-store',
>         'redux-thunk',
>         'reselect',
>         'rxjs',
>         'styled-components',
>         'subscriptions-transport-ws' ] },
>   output:
>    { filename: 'vendor_web.[hash]_dll.js',
>      path: 'dllPath',
>      library: 'vendor_web' } }
> spin debug web =  { name: 'web',
>   devtool: '#cheap-module-source-map',
>   module:
>    { rules:
>       [ { test: /\.(png|ico|jpg|xml)$/,
>           use:
>            { loader: 'loaderPath',
>              options: { name: '[hash].[ext]', limit: 100000 } } },
>         { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
>           use:
>            { loader: 'loaderPath',
>              options: { name: './assets/[hash].[ext]', limit: 100000 } } },
>         { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
>           use:
>            { loader: 'loaderPath',
>              options: { name: './assets/[hash].[ext]' } } },
>         { test: /\.css$/,
>           use:
>            [ { loader: 'loaderPath' },
>              { loader: 'loaderPath',
>                options: { sourceMap: true, importLoaders: 1 } },
>              { loader: 'loaderPath',
>                options: { plugins: [Function: plugins], sourceMap: true } } ] },
>         { test: /\.graphqls/,
>           use: 'usePath' },
>         { test: /\.(graphql|gql)$/,
>           exclude: /node_modules/,
>           use: [ 'usePath' ] },
>         { test: /\.tsx?$/,
>           use:
>            [ { loader: 'usePath',
>                options: { configFileName: 'path' } } ] },
>         { test: /\.html$/,
>           loader: 'usePath' } ] },
>   resolve:
>    { modules:
>       [ 'node_modulesPath',
>         'node_modules' ],
>      extensions:
>       [ '.web.tsx',
>         '.web.ts',
>         '.web.jsx',
>         '.web.js',
>         '.tsx',
>         '.ts',
>         '.jsx',
>         '.js' ] },
>   watchOptions: { ignored: /build/ },
>   bail: false,
>   plugins:
>    [ NamedModulesPlugin { options: {} },
>      HotModuleReplacementPlugin {
>        options: {},
>        multiStep: undefined,
>        fullBuildTimeout: 200,
>        requestTimeout: 10000 },
>      NoEmitOnErrorsPlugin {},
>      DefinePlugin {
>        definitions:
>         { __CLIENT__: true,
>           __SERVER__: false,
>           __SSR__: false,
>           __DEV__: true,
>           'process.env.NODE_ENV': '"development"',
>           __BACKEND_URL__: '"http://localhost:8080"',
>           __GRAPHQL_URL__: '\'http://localhost:8080/graphql\'' } },
>      ManifestPlugin {
>        opts:
>         { basePath: '',
>           publicPath: '',
>           fileName: 'assets.json',
>           stripSrc: null,
>           transformExtensions: /^(gz|map)$/i,
>           writeToFileEmit: false,
>           cache: null,
>           seed: null,
>           filter: null,
>           map: null,
>           reduce: null } },
>      HtmlWebpackPlugin {
>        options:
>         { template: './tools/html-plugin-template.ejs',
>           filename: 'index.html',
>           hash: false,
>           inject: 'body',
>           compile: true,
>           favicon: false,
>           minify: false,
>           cache: true,
>           showErrors: true,
>           chunks: 'all',
>           excludeChunks: [],
>           title: 'Webpack App',
>           xhtml: false } },
>      DefinePlugin { definitions: { __PERSIST_GQL__: false } },
>      PersistGraphQLPlugin {
>        options: { moduleName: 'optionsPath' },
>        _listeners: [],
>        virtualModules: VirtualModulesPlugin { _staticModules: undefined } },
>      CheckerPlugin {} ],
>   node: { fs: 'empty', net: 'empty', tls: 'empty' },
>   entry: { index: [ 'entryPath' ] },
>   output:
>    { filename: '[name].[hash].js',
>      path: 'myPath',
>      publicPath: '/' },
>   devServer:
>    { hot: true,
>      contentBase: '/',
>      publicPath: '/',
>      headers: { 'Access-Control-Allow-Origin': '*' },
>      quiet: false,
>      noInfo: true,
>      historyApiFallback: true,
>      stats: { colors: true, chunkModules: false },
>      port: 3009,
>      proxy: { '!/*.hot-update.{json,js}': { target: 'http://localhost:8080', logLevel: 'info' } } } }

**Comment by vlasenko** [comment]
@lyudad We set `node: { __dirname: true }` when `stack` has `server` as a target platform. Your `stack` doesn't specify `server`. I wonder why it works at all this way. Your `stack`, should include one of `server`, `web`, `android` or `ios`.

**Comment by lyudad** [comment]
missed it, yes found it on `server` but __dirname still not work

**Comment by vlasenko** [comment]
Check if target platform included into `stack` is added and published in `spinjs@0.4.21`

**Comment by vlasenko** [comment]
@lyudad If `__dirname` doesn't work, why are you closing the issue?

**Comment by vlasenko** [comment]
@lyudad Could you add more details about problem you see? How can I reproduce it?

**Comment by lyudad** [comment]
close, as I thought that problem was with webpack, but look like it ok. Updated to spinjs@0.4.21, but I have the same issue

**Comment by vlasenko** [comment]
@lyudad Yeah, look the clarification here:
https://github.com/webpack/webpack/issues/2010
I think we should actually set __dirname to false for server target

**Comment by vlasenko** [comment]
@lyudad Okay, I have dropped setting `node: { __dirname: true }` in `spinjs@0.4.22`. Could you check if it fixes your issue?

**Comment by lyudad** [comment]
I think it's because I use code in in my package outside the server folder. As in server folder everything ok.

**Comment by vlasenko** [comment]
@lyudad I think what you really want is webpack substitution of `__dirname` for non-server builds. I have pushed settings `node: { __dirname: true }` for client bundles in `spinjs@0.4.23`

**Comment by vlasenko** [comment]
Closing this issue for now, if there will be new information about the problem, please reopen
