### ISSUE TITLE
Broken `historyApiFallback`

### ISSUE THREAD

**Issue by msaspence** [sysgears/spinjs#25]
I can't get my app to properly implement `historyApiFallback` the proxy gets in the way. Even if I hack at the `spinjs` source to disable the proxy I webpack can't find anything other than the index.

**Comment by vlasenko** [comment]
@msaspence Could you provide more details, so that I can reproduce the problem and fix it? I'm not quite understand what your problem is, at the moment...

**Comment by msaspence** [comment]
https://github.com/msaspence/spinjstest

Here's an example (node_modules included)

When trying to use spinjs for a single page app and I want to route everything to the `index.html`, although `historyApiFallback` is turned on the web pack proxy config doesn't let it.

**Comment by vlasenko** [comment]
@msaspence In `spinjs@0.4.27` onwards request proxying will be only turned on if `options.ssr` is true. So proxy should not stay on your way.

**Comment by vlasenko** [comment]
@msaspence In `spinjs@0.4.28` proxying from Webpack dev server to backend is disabled by default. To enable it, set `devProxy: true` on a builder or in spin options.

**Comment by msaspence** [comment]
@vlasenko I'm no longer being proxied, but I get a `Cannot GET` page for anything other than the index page.

**Comment by vlasenko** [comment]
@msaspence Do you think this is incorrect? You can check generated webpack config via `spin -v watch`, it should have historyApiFallback: true and no proxying

**Comment by msaspence** [comment]
@vlasenko The configuration looks good, I'm at a lose as to why the routing is still not functioning correctly.

**Comment by vlasenko** [comment]
@msaspence Okay, I'm looking at this too. Meanwhile I have added quick way to hack generated webpack config in `spinjs@0.4.29`, you can add `webpackConfig` option to the builder and write your additional rules or override generated webpack rules from there.

**Comment by vlasenko** [comment]
@msaspence I think you should really play with example from here:
https://github.com/webpack/webpack-dev-server/tree/master/examples/history-api-fallback
to check how historyApiFallback works

**Comment by vlasenko** [comment]
@msaspence Okay, I think I have found the root of the problem. In `spinjs` we are using, `webpack-dev-middleware` as a more lightweight alternative to `webpack-dev-server`. And `historyApiFallback` is supported only in `webpack-dev-server`, not `webpack-dev-middleware`

**Comment by vlasenko** [comment]
@msaspence We have switched to `webpack-dev-middleware` from `webpack-dev-server` to handle complexities of `android` and `ios` target platform, but I think for `web` platform we should really use `webpack-dev-server` as a more feature complete solution for this platform. I'm going to implement and test this tomorrow

**Comment by msaspence** [comment]
Does look like there are other problems this could throw up, so sounds like a good idea. Otherwise https://github.com/bripkens/connect-history-api-fallback is probably what we are after for this specific problem.

**Comment by msaspence** [comment]
Yaaaas! Will have a proper play with this on my actual project this evening

Thanks man

**Comment by vlasenko** [comment]
Great! No problems!
