### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by wojcikiewiczm** [sysgears/spinjs#26]
Hello I want to ask. Is possible to add custom webpack plugins? For example I want to use GZIP compression (https://github.com/webpack-contrib/compression-webpack-plugin). If it's possible how can I do it. Thank you 😄

**Comment by vlasenko** [comment]
@wojcikiewiczm Yes, you can provide `webpackConfig` option for that in JavaScript config file `.spinrc.js`:
https://github.com/sysgears/spinjs#webpack-babel-and-other-tool-specific-config-merging
