### ISSUE TITLE
Add babel-plugin-import for modular imports

### ISSUE THREAD

**Issue by papigers** [sysgears/spinjs#29]
https://github.com/ant-design/babel-plugin-import

Useful for projects where antd or material-ui is used.
Maybe you should add `antd` and `material-ui` to the stack list, with each adding this babel plugin. For material-ui I guess setup should be even more complicated since it uses JSS.

Thoughts?

BTW, great project :)

**Comment by vlasenko** [comment]
@papigers Yes, good idea. Maybe you would be willing to submit Pull Request? I'm not sure where I will have time to add this, but would be happy to help with PR

**Comment by papigers** [comment]
@vlasenko No problem, can you guide me on where to start? Should I create a dedicated plugin for material-ui and another one for antd?

**Comment by vlasenko** [comment]
@papigers Yes, that would be the best way to go
