### ISSUE TITLE
vendor_web is not defined

### ISSUE THREAD

**Issue by lyudad** [sysgears/spinjs#30]
"spinjs": "^0.4.18"

![2017-12-14 12 24 42](https://user-images.githubusercontent.com/25103090/33987564-026057f2-e0ca-11e7-83a3-ddd36be45be4.png)

sometime if set "spinjs": "0.4.18", everything work

**Comment by mairh** [comment]
Try the latest version `"spinjs": "^0.4.53"`

**Comment by vlasenko** [comment]
@lyudad Try to remove your `build` folder and restart `yarn watch`

**Comment by lyudad** [comment]
remove `build` folder was first that I have tried. 
I have tried `"spinjs": "^0.4.53"` but have other error :
`webpack-for-webDll warn Error checking vendor bundle vendor_web, regenerating it... SyntaxError: Unexpected end of JSON input`

![2017-12-14 12 54 38](https://user-images.githubusercontent.com/25103090/33988781-1d4bc476-e0ce-11e7-96af-1fc4f26bd131.png)

**Comment by vlasenko** [comment]
@lyudad This is not a fatal error, it should regenerate bundle after that and save it on disk and continue

**Comment by lyudad** [comment]
I understand that warn is not error, but backend was stopped in this case

**Comment by vlasenko** [comment]
Try to start it manually after that via: `node ./servers/backend-server/build/server/index.js`. Substitute correct path to the generated backend file

**Comment by vlasenko** [comment]
Latest `spinjs` dumps command to start the backend to terminal, use that command to start backend manually
