### ISSUE TITLE
Using with code coverage [nyc + babel-plugin-istanbul]

### ISSUE THREAD

**Issue by 4matic** [sysgears/spinjs#37]
How can I use this module to get coverage of my code? (**nyc + babel-plugin-istanbul**)
I figured out that under the hood you are using **[mocha-webpack](https://github.com/zinserjan/mocha-webpack)**.
I found :mag: [good issue](https://github.com/zinserjan/mocha-webpack/issues/19) for that
How about using with **spinjs**?

Also I have found lines where is possible change path for that:
https://github.com/sysgears/spinjs/blob/d76a58b4512ecf3bc6dda5b336eac135d47a1efa/src/executor.ts#L966-L975

**Comment by vlasenko** [comment]
@4matic Lets discuss in the chat:
https://gitter.im/sysgears/spinjs

To start, search `babelConfig` option in spinjs docs:
https://github.com/sysgears/spinjs#concepts

**Comment by 4matic** [comment]
After a little discuss I found a way to apply this in my project:

First I used to try this for **babelConfig** option in **.spinrc.js** file as it is described [here](https://www.npmjs.com/package/nyc#use-with-babel-plugin-istanbul-for-babel-support)
```javascript
{
  "options":{
    "babelConfig": {
      "presets": ["env"],
        "env": {
        "test": {
          "plugins": ["istanbul"]
        }
      }
    }
  }
}
```
But unfortunately this not worked...

So after that I tried other solution:
For this I used [cross-env](https://www.npmjs.com/package/cross-env) to set `NODE_ENV` to **test**:
`nyc cross-env NODE_ENV=test spin test -t 15000 --full-trace --exit \"src/**/*.spec.js\"`

And also added some condition to my **.spinrc.js** file:
```javascript
if (process.env.NODE_ENV === 'test') {
  config.options.babelConfig = {
    "plugins": ["istanbul"]
  }
}
```

That's all.
Thanks to @vlasenko for pointing out the correct direction of the idea.

**Comment by vlasenko** [comment]
@4matic Thank you very much for writing the solution here!
