### ISSUE TITLE
server restart when webpack throws warning [HMR] Cannot find update.

### ISSUE THREAD

**Issue by veeramarni** [sysgears/spinjs#45]
When we externalize the `node_modules`, webpack hot loader on the server side ignores any (`lerna`) packages that compiled recently by throwing the warning. Instead, we want the server to restart when we see this warning. In the earlier version, like 0.4.18 I noticed the server restart but in the latest version, I don't see this happening.  

```
[HMR] Cannot find update.
```

I'm using this workaround, to check the `status` idle (noticed the status as `idle` when it throws the warning), if idle I'm exiting the process so it restarts. 

```
if (module.hot) {
    module.hot.status(event => {
        logger.trace(event);
        if (event === 'abort' || event === 'fail') {
            logger.error('HMR error status: ' + event);
            // Signal webpack.run.js to do full-reload of the back-end
            process.exit(250);
        }
        if (event === 'idle') {
            process.exit(250);
        }
    });

    module.hot.accept();
}
```

Do you have any better suggestion?

**Comment by vlasenko** [comment]
@veeramarni Well, you can try to search through the guts of webpack to find a better solution, but your solution looks good enough to me

**Comment by veeramarni** [comment]
closing it as the workaround suffice.
