### ISSUE TITLE
Remove WebpackPlugin's LoaderOptionsPlugin

### ISSUE THREAD

**Issue by clodal** [sysgears/spinjs#5]
### Issue
In `spinjs/src/plugins/WebpackPlugin.ts:61`, remove `LoaderOptionsPlugin` from the plugins array as it seems like a legacy plugin from webpack v1/v2.

### Purpose
Seems like the purpose of this plugin being added to spinjs is to provide minification for the loaders (i'm guessing for performance reasons). However, this does not seem like the common practice for minification. Furthermore, the plugin seems to only have been made for webpack v1 to v2 migration in the past. This is according to the [webpack docs on the LoaderOptionsPlugin:](https://webpack.js.org/plugins/loader-options-plugin/)

> This plugin will be removed in the future as it only exists for migration.

~Most importantly, it causes side-effects with webpack's main UglifyJS plugin as I have experienced it from a downstream application using spinjs. Removing this LoaderOptionsPlugin or disabling the minify option solves the issue.~

**Update: There is no side-effect, I just realised it is another issue. But i still don't think we need this plugin. Perhaps consider to remove this still?**

### Related code
```
// spinjs/src/plugins/WebpackPlugin.ts
43    const loaderOpts: any = { minimize: builder.minify };
...
61    plugins.push(new webpack.LoaderOptionsPlugin(loaderOpts));
```
### Recommendation
1. Either, remove it completely
2. Or, expose config to disable this plugin

@vlasenko Let me know what you think? Thanks, happy to submit PR!

**Comment by vlasenko** [comment]
@clodal Yes, lets remove it. I would be glad to accept PR from you - that removes this plugin
