### ISSUE TITLE
Remove UglifyJsPlugin and expose Webpack v4 Optimization config

### ISSUE THREAD

**Issue by clodal** [sysgears/spinjs#7]
### Issue
In `spinjs/src/plugins/WebpackPlugin.ts:54`, we are manually adding UglifyJSPlugin like so:
```
53.   const UglifyJsPlugin = builder.require('uglifyjs-webpack-plugin');
54.   plugins.push(new UglifyJsPlugin(uglifyOpts));
```
However, since Webpack v4, setting `mode` to `production` should already perform UglifyJs optimisations by default ([see webpack discussion](
https://github.com/webpack/webpack/issues/6075)).

Reference: 
- https://stackoverflow.com/questions/51243247/webpack-4-and-uglify-plugin-typeerror-cannot-read-property-length-of-undefin

Including UglifyJsPlugin manually like how we do now, causes side-effects during the compilation, as I have faced in my downstream app and also evident from the stackoverflow question above.

### Recommendation
Remove the UglifyJsPlugin and ensure minification is done by default with [webpack v4’s `optimization.minize`](https://webpack.js.org/configuration/optimization/#optimization-minimize). Also expose the `optimization.minimizer` config to allow end-users to override the default minimizer.

Reference:
- https://stackoverflow.com/questions/49053215/webpack-4-how-to-configure-minimize

— 
Happy to submit PR, thanks!

**Comment by vlasenko** [comment]
@clodal Thanks, I will be happy to accept PRs on both of your issues here. Please note that you can override `optimization.minimize` as well as any other webpack config parts via `webpackConfig` option already:
https://github.com/sysgears/spinjs#webpack-babel-and-other-tool-specific-config-merging
